const {test}=require('node:test');
const assert=require('node:assert/strict');
const db=require('../src/db');
const {signToken}=require('../src/utils/tokens');
const {runTaskReminders}=require('../src/utils/taskReminders');
const {formatActivity}=require('../src/utils/activityFeed');
const express=require('express');require('express-async-errors');
process.env.JWT_SECRET='task-tests-only';
const ids={admin:'11111111-1111-4111-8111-111111111111',sam:'22222222-2222-4222-8222-222222222222',other:'33333333-3333-4333-8333-333333333333',task:'44444444-4444-4444-8444-444444444444',lead:'55555555-5555-4555-8555-555555555555'};
test('task API enforces authentication, ownership, validation, atomic writes and idempotent completion',async()=>{
 const calls=[];let complete=false,failAudit=false,creator=ids.admin;
 const query=async(sql,p=[])=>{calls.push([sql,p]);
 if(sql.startsWith('SELECT id FROM users'))return {rows:[{id:p[0]}]};
 if(sql.startsWith('SELECT business_name'))return {rows:[{business_name:'Cafe',salesman_id:ids.sam}]};
 if(sql.includes('created_by=$2')&&p[1]&&creator!==p[1])return {rows:[]};
 if(sql.startsWith('SELECT * FROM crm_tasks'))return {rows:p[1]&&p[1]!==ids.sam?[]:[{id:ids.task,title:'Visit cafe',assigned_to:ids.sam,status:complete?'completed':'pending'}]};
 if(sql.startsWith('INSERT INTO crm_tasks'))return {rows:[{id:ids.task,title:p[0]}]};
 if(sql.startsWith('UPDATE crm_tasks'))complete=true;
 if(sql.startsWith('INSERT INTO activity_logs')&&failAudit)throw Error('audit unavailable');
 if(sql.startsWith('SELECT count'))return {rows:[{pending:1}]};
 return {rows:[]};};
 db.query=query;db.pool.connect=async()=>({query,release(){}});
 const app=express();app.use(express.json());app.use('/tasks',require('../src/routes/tasks.routes'));app.use((e,q,r,n)=>r.status(500).json({error:e.message}));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const request=async(user,path,body,method=body?'POST':'GET')=>{const headers={'Content-Type':'application/json'};if(user)headers.Authorization='Bearer '+signToken({id:ids[user],role:user==='admin'?'admin':'salesman'});return fetch(`http://127.0.0.1:${server.address().port}/tasks${path}`,{method,headers,...(body?{body:JSON.stringify(body)}:{})})};
 const data={title:'Visit cafe',assignedTo:ids.sam,leadId:ids.lead,dueAt:'2026-09-18T05:30:00Z'};
 try{
 assert.equal((await request(null,'/')).status,401);
 assert.equal((await request('sam','/',{...data,assignedTo:ids.other})).status,403);
 assert.equal((await request('admin','/',{...data,assignedTo:ids.other})).status,400);
 assert.equal((await request('sam','/',{...data,title:' '})).status,400);
 assert.equal((await request('sam','/',{...data,dueAt:'invalid'})).status,400);
 assert.equal((await request('admin','/',data)).status,201);
 assert.ok(calls.some(([s])=>s==='COMMIT'));assert.ok(calls.some(([s])=>s.startsWith('INSERT INTO task_notifications')));
 assert.equal((await request('other','/'+ids.task+'/complete',{note:'done'},'PATCH')).status,404);
 assert.equal((await request('sam','/'+ids.task+'/complete',{note:'Owner requested quote'},'PATCH')).status,200);
 const auditBefore=calls.filter(([s])=>s.startsWith('INSERT INTO activity_logs')).length;
 assert.equal((await request('sam','/'+ids.task+'/complete',{note:'repeat'},'PATCH')).status,200);
 assert.equal(calls.filter(([s])=>s.startsWith('INSERT INTO activity_logs')).length,auditBefore);
 await request('sam','/?filter=overdue&offset=50');
 const list=calls.findLast(([s])=>s.includes('LIMIT 51'));
 assert.match(list[0],/t.assigned_to=\$1/);assert.equal(list[1][0],ids.sam);assert.equal(list[1][2],50);
 assert.equal((await request('sam','/?offset=-1')).status,400);
 await request('sam','/notifications/read',{ids:[ids.task]});
 assert.ok(calls.some(([s,p])=>s.includes('user_id=$1 AND id=ANY')&&p[0]===ids.sam));
 assert.equal((await request('sam','/'+ids.task,null,'DELETE')).status,404);
 assert.equal((await request('other','/'+ids.task,null,'DELETE')).status,404);
 creator=ids.sam;
 assert.equal((await request('sam','/'+ids.task,null,'DELETE')).status,200);
 assert.ok(calls.some(([s])=>s.startsWith('DELETE FROM crm_tasks')));
 creator=ids.admin;
 assert.equal((await request('admin','/'+ids.task,null,'DELETE')).status,200);
 failAudit=true;const deletesBefore=calls.filter(([s])=>s.startsWith('DELETE FROM crm_tasks')).length;
 assert.equal((await request('admin','/'+ids.task,null,'DELETE')).status,500);
 assert.equal(calls.filter(([s])=>s.startsWith('DELETE FROM crm_tasks')).length,deletesBefore);
 assert.equal(calls.at(-1)[0],'ROLLBACK');
 failAudit=true;assert.equal((await request('admin','/',data)).status,500);assert.equal(calls.at(-1)[0],'ROLLBACK');
 }finally{await new Promise(r=>server.close(r));}
});
test('daily task reminder claims are deduplicated and exclude completed/inactive users',async()=>{
 let sql;const result=await runTaskReminders(async s=>{sql=s;return{rows:[{id:'1'}]}});
 assert.deepEqual(result,{taskReminders:1});assert.match(sql,/ON CONFLICT.*DO NOTHING/);assert.match(sql,/t.status IN \('pending','in_progress'\)/);assert.match(sql,/u.is_active=true/);assert.match(sql,/Asia\/Kolkata/);
});
test('task activity identifies actor and action without exposing raw metadata',()=>{
 const r=formatActivity({action:'task.completed',actor_name:'Anand',task_title:'Visit cafe'});
 assert.equal(r.description,'Anand completed task “Visit cafe”.');assert.equal(r.metadata,undefined);
});
