const express=require('express'),db=require('../db');
const {requireAuth,requireRole}=require('../middleware/auth');
const {UUID,bad,str,date,validateConfig,buildSnapshot,canShare,customerSummary}=require('../utils/quotations');
const {renderQuotationPDF}=require('../utils/quotationPDF');
const router=express.Router();
router.use(requireAuth);
router.use(async(req,res,next)=>{res.set('Cache-Control','no-store');const {rows}=await db.query('SELECT id FROM users WHERE id=$1 AND role=$2 AND is_active=true',[req.user.id,req.user.role]);if(!rows.length||!['admin','salesman'].includes(req.user.role))throw bad('Active account required',403);next();});
router.get('/settings',async(req,res)=>res.json((await db.query('SELECT version,config FROM quotation_settings WHERE id=1')).rows[0]));
router.put('/settings',requireRole('admin'),async(req,res)=>{const config=validateConfig(req.body.config);if(!Number.isInteger(req.body.version))throw bad('Invalid settings version');const {rows}=await db.query('UPDATE quotation_settings SET config=$1::jsonb,version=version+1,updated_at=now() WHERE id=1 AND version=$2 RETURNING version,config',[JSON.stringify(config),req.body.version]);if(!rows.length)throw bad('Settings changed. Reload before saving.',409);res.json(rows[0]);});
router.get('/customers',async(req,res)=>{const search=str(req.query.search||'',100);const {rows}=await db.query(`SELECT id,business_name,contact_name,phone FROM leads WHERE ($1::uuid IS NULL OR salesman_id=$1) AND position(lower($2) in lower(business_name))>0 ORDER BY business_name,id LIMIT 30`,[req.user.role==='admin'?null:req.user.id,search]);res.json({customers:rows});});
router.get('/alerts',async(req,res)=>{const {rows}=await db.query(`SELECT a.*,r.snapshot->'customer'->>'name' AS customer_name FROM quotation_alerts a JOIN quotations q ON q.id=a.quote_id JOIN quotation_revisions r ON r.quote_id=q.id AND r.revision=a.revision WHERE a.user_id=$1 AND a.read_at IS NULL AND (q.owner_id=$1 OR $2='admin') ORDER BY a.created_at DESC LIMIT 30`,[req.user.id,req.user.role]);res.json({alerts:rows});});
router.post('/alerts/read',async(req,res)=>{const ids=req.body.ids;if(!Array.isArray(ids)||ids.length>30||ids.some(id=>!UUID.test(id)))throw bad('Invalid alerts');await db.query('UPDATE quotation_alerts SET read_at=now() WHERE user_id=$1 AND id=ANY($2::uuid[])',[req.user.id,ids]);res.json({ok:true});});
router.get('/',async(req,res)=>{const offset=Number(req.query.offset||0),search=str(req.query.search||'',100),status=req.query.status||'';if(!Number.isSafeInteger(offset)||offset<0||offset>100000||!['','pending_approval','ready','sent','accepted','rejected','changes_requested'].includes(status))throw bad('Invalid page or status');const {rows}=await db.query(`SELECT q.*,r.status,r.version,r.expires_on::text,r.follow_up::text,r.snapshot->'customer'->>'name' AS customer_name,r.snapshot->>'prefix' AS prefix,r.snapshot->>'currency' AS currency,r.snapshot->>'totalMinor' AS total_minor,u.full_name AS owner_name
 FROM quotations q JOIN quotation_revisions r ON r.quote_id=q.id AND r.revision=q.current_revision LEFT JOIN users u ON u.id=q.owner_id
 WHERE ($1::uuid IS NULL OR q.owner_id=$1) AND ($2='' OR r.status=$2) AND position(lower($3) in lower(r.snapshot->'customer'->>'name'))>0 ORDER BY q.updated_at DESC,q.id LIMIT 31 OFFSET $4`,[req.user.role==='admin'?null:req.user.id,status,search,offset]);res.json({quotes:rows.slice(0,30),hasMore:rows.length>30});});
router.param('id',(req,res,next,id)=>next(UUID.test(id)?undefined:bad('Invalid quotation')));
async function transaction(fn){const c=await db.pool.connect();try{await c.query('BEGIN');const result=await fn(c.query.bind(c));await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
async function getQuote(query,user,id,lock=false){const {rows}=await query(`SELECT * FROM quotations WHERE id=$1 AND ($2::uuid IS NULL OR owner_id=$2)${lock?' FOR UPDATE':''}`,[id,user.role==='admin'?null:user.id]);if(!rows.length)throw bad('Quotation not found',404);return rows[0];}
async function getRevision(query,q,revision=q.current_revision){const {rows}=await query('SELECT *,expires_on::text AS expires_on,follow_up::text AS follow_up FROM quotation_revisions WHERE quote_id=$1 AND revision=$2',[q.id,revision]);if(!rows.length)throw bad('Revision not found',404);return rows[0];}
async function event(query,q,rev,user,action,note=''){await query('INSERT INTO quotation_events(quote_id,revision,actor_id,action,note) VALUES($1,$2,$3,$4,$5)',[q.id,rev,user.id,action,note]);}
async function alerts(query,q,r,kind){if(kind==='approval')await query(`INSERT INTO quotation_alerts(user_id,quote_id,revision,kind) SELECT id,$1,$2,'approval' FROM users WHERE role='admin' AND is_active=true ON CONFLICT DO NOTHING`,[q.id,r]);else if(q.owner_id)await query('INSERT INTO quotation_alerts(user_id,quote_id,revision,kind) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[q.owner_id,q.id,r,kind]);}
async function createRevision(query,req,q){
 const {rows}=await query('SELECT version,config FROM quotation_settings WHERE id=1 FOR SHARE');const settings=rows[0];if(req.body.settingsVersion!==settings.version)throw bad('Prices or terms changed. Reload quotation settings before creating.',409);
 let customer=req.body.customer;
 if(q.lead_id){const {rows:leads}=await query('SELECT business_name,contact_name,phone FROM leads WHERE id=$1 AND ($2::uuid IS NULL OR salesman_id=$2) FOR SHARE',[q.lead_id,req.user.role==='admin'?null:req.user.id]);if(!leads.length)throw bad('Lead not found or no longer assigned to you',404);customer={name:leads[0].business_name,contact:leads[0].contact_name,phone:leads[0].phone};}
 if(!customer)throw bad('Enter customer details');const snapshot=buildSnapshot(settings.config,req.body,customer),followup=date(req.body.followUp,true);
 const status=snapshot.discount>snapshot.discountLimit?'pending_approval':'ready';
 await query('INSERT INTO quotation_revisions(quote_id,revision,snapshot,status,follow_up,expires_on,created_by) VALUES($1,$2,$3::jsonb,$4,$5,$6,$7)',[q.id,q.current_revision,JSON.stringify(snapshot),status,followup,snapshot.expiresOn,req.user.id]);
 await event(query,q,q.current_revision,req.user,'created',snapshot.reason);if(status==='pending_approval')await alerts(query,q,q.current_revision,'approval');return {id:q.id};
}
router.post('/',async(req,res)=>res.status(201).json(await transaction(async query=>{const leadId=req.body.leadId||null;if(leadId&&!UUID.test(leadId))throw bad('Invalid lead');const {rows}=await query('INSERT INTO quotations(owner_id,lead_id) VALUES($1,$2) RETURNING *',[req.user.id,leadId]);return createRevision(query,req,rows[0]);})));
router.get('/:id',async(req,res)=>{const q=await getQuote(db.query,req.user,req.params.id),current=await getRevision(db.query,q);const {rows:revisions}=await db.query('SELECT revision,status,created_at,snapshot->>\'totalMinor\' AS total_minor,snapshot->>\'currency\' AS currency FROM quotation_revisions WHERE quote_id=$1 ORDER BY revision DESC',[q.id]);const {rows:events}=await db.query('SELECT e.*,u.full_name AS actor_name FROM quotation_events e LEFT JOIN users u ON u.id=e.actor_id WHERE quote_id=$1 ORDER BY e.id DESC LIMIT 200',[q.id]);res.json({quote:q,current,revisions,events});});
router.post('/:id/revise',async(req,res)=>res.status(201).json(await transaction(async query=>{const q=await getQuote(query,req.user,req.params.id,true);if(req.body.currentRevision!==q.current_revision)throw bad('Quotation changed. Reload before revising.',409);if(q.current_revision>=100)throw bad('Revision limit reached');q.current_revision++;await query('UPDATE quotations SET current_revision=$2,updated_at=now() WHERE id=$1',[q.id,q.current_revision]);await query('UPDATE quotation_alerts SET read_at=now() WHERE quote_id=$1 AND read_at IS NULL',[q.id]);return createRevision(query,req,q);})));
router.post('/:id/action',async(req,res)=>res.json(await transaction(async query=>{
 const q=await getQuote(query,req.user,req.params.id,true),r=await getRevision(query,q),b=req.body;if(b.revision!==q.current_revision||b.version!==r.version)throw bad('Quotation changed. Reload before updating.',409);
 const note=str(b.note||'',1000);let status=r.status,sent=false,followUp=r.follow_up;
 if(['approve','request_changes'].includes(b.action)){if(req.user.role!=='admin')throw bad('Requires admin role',403);if(r.status!=='pending_approval')throw bad('No pending approval',409);status=b.action==='approve'?'ready':'changes_requested';await alerts(query,q,r.revision,b.action==='approve'?'approved':'changes_requested');await query("UPDATE quotation_alerts SET read_at=now() WHERE quote_id=$1 AND revision=$2 AND kind='approval'",[q.id,r.revision]);}
 else if(b.action==='sent'){canShare(r);if(r.status!=='ready')throw bad('Already sent or closed',409);status='sent';sent=true;}
 else if(['accepted','rejected','changes_requested'].includes(b.action)){if(r.status!=='sent')throw bad('Mark quotation sent before recording a response',409);status=b.action;await query('UPDATE quotation_alerts SET read_at=now() WHERE quote_id=$1 AND read_at IS NULL',[q.id]);}
 else if(b.action==='follow_up'){followUp=date(b.followUp,true);await query("UPDATE quotation_alerts SET read_at=now() WHERE quote_id=$1 AND kind='follow_up' AND read_at IS NULL",[q.id]);}
 else throw bad('Unknown quotation action');
 await query('UPDATE quotation_revisions SET status=$3,version=version+1,follow_up=$4,sent_at=CASE WHEN $5 THEN now() ELSE sent_at END WHERE quote_id=$1 AND revision=$2',[q.id,r.revision,status,followUp,sent]);await query('UPDATE quotations SET updated_at=now() WHERE id=$1',[q.id]);await event(query,q,r.revision,req.user,b.action,note);return {ok:true};
})));
router.get('/:id/summary',async(req,res)=>{const q=await getQuote(db.query,req.user,req.params.id);res.json(customerSummary(q,await getRevision(db.query,q)));});
router.get('/:id/pdf',async(req,res)=>{const q=await getQuote(db.query,req.user,req.params.id);const revision=req.query.revision===undefined?q.current_revision:Number(req.query.revision);if(!Number.isInteger(revision)||revision<1||revision>q.current_revision)throw bad('Invalid revision');const r=await getRevision(db.query,q,revision);if(!['ready','sent','accepted'].includes(r.status))throw bad('Quotation is not approved for PDF export',409);const buffer=await renderQuotationPDF(q,r);res.set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="quotation-${q.number}-r${revision}.pdf"`});res.send(buffer);});
router.use((err,req,res,next)=>{if(err.status)return res.status(err.status).json({error:err.message});next(err);});
module.exports=router;
